frr version 10.5.1
frr defaults traditional
hostname router-ns
hostname vikky
service integrated-vtysh-config
!
route-map ALLOW-ALL permit 10
exit
!
router bgp 65001
 bgp router-id 192.168.100.10
 neighbor 192.168.100.20 remote-as 65002
 neighbor 192.168.100.20 password SecretBGPPassword123
 !
 address-family ipv4 unicast
  network 192.168.10.0/24
  network 192.168.20.0/24
  network 192.168.30.0/24
  network 192.168.40.0/24
  neighbor 192.168.100.20 route-map ALLOW-ALL in
  neighbor 192.168.100.20 route-map ALLOW-ALL out
 exit-address-family
exit
!
