frr version 10.5.1
frr defaults traditional
hostname router2
hostname vikky
service integrated-vtysh-config
!
ip prefix-list PL-ALLOW seq 5 permit 192.168.20.0/24
!
route-map ALLOW-ALL permit 10
exit
!
route-map RM-IN permit 10
 match ip address prefix-list PL-ALLOW
exit
!
route-map RM-SET-LOCALPREF permit 10
 set local-preference 200
exit
!
router bgp 65002
 bgp router-id 192.168.100.20
 neighbor 192.168.100.10 remote-as 65001
 neighbor 192.168.100.10 password SecretBGPPassword123
 neighbor 192.168.200.2 remote-as 65002
 neighbor 192.168.200.2 update-source lo
 !
 address-family ipv4 unicast
  neighbor 192.168.100.10 route-map RM-SET-LOCALPREF in
  neighbor 192.168.100.10 route-map ALLOW-ALL out
 exit-address-family
exit
!
