---
- name: Configure FRR BGP
  hosts: routers
  connection: local
  become: yes
  gather_facts: no

  tasks:
    - name: Advertise 192.168.50.0/24 from router-ns
      ansible.builtin.shell: |
        ip netns exec router-ns vtysh --vty_socket /run/frr-router-ns \
        -c "configure terminal" \
        -c "router bgp 65001" \
        -c "network 192.168.50.0/24" \
        -c "end"
      changed_when: true

    - name: Advertise 192.168.60.0/24 from router2
      ansible.builtin.shell: |
        ip netns exec router2 vtysh --vty_socket /run/frr-router2 \
        -c "configure terminal" \
        -c "router bgp 65002" \
        -c "network 192.168.60.0/24" \
        -c "end"
      changed_when: true
